globals:
  $: true
rules:
  # Possible Errors
  no-console: 0 # switch this to 2 to check if you have some console.logs trailing
  # Best Practices
  block-scoped-var: 1
  curly:
    - 1
    - multi-line
  default-case: 1
  eqeqeq: 2
  guard-for-in: 2
  no-caller: 2
  no-eq-null: 2
  no-eval: 2
  no-multi-spaces: 2
  no-new: 2
  no-redeclare: 2
  # Variables
  no-undef: 0
  no-unused-vars: 1
  no-use-before-define: 0
  # Style
  array-bracket-spacing: 2
  brace-style:
    - 2
    - 1tbs
    - allowSingleLine: true
  camelcase: 0
  comma-dangle: 0
  comma-spacing:
    - 2
    - after: true
  comma-style:
    - 2
    - last
  computed-property-spacing: 2
  consistent-this:
    - 1
    - this$1
  indent:
    - 2
    - tab
    - SwitchCase: 1
  key-spacing: 2
  linebreak-style: 0
  new-cap: 0
  no-bitwise: 2
  no-mixed-spaces-and-tabs: 2
  no-nested-ternary: 0
  no-trailing-spaces: 2
  one-var:
    - 2
    - never
  quotes:
    - 2
    - single
    - avoidEscape: true
  semi:
    - 2
    - always
  space-before-function-paren:
    - 2
    - never
  space-in-parens: 2
  # ES6
  no-var: 2
  prefer-const: 1
env:
  es6: true
  browser: true
  node: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 2018
  sourceType: module
