options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
rules:
  attribute-quotes: 2
  bem-depth: 0
  border-zero: 2
  brace-style:
    - 2
    - allow-single-line: false
  class-name-format:
    - 0
    - allow-leading-underscore: false
    - convention: hyphenatedbem
  clean-import-paths: 0
  declarations-before-nesting: 1
  empty-args: 2
  empty-line-between-blocks: 1
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline: 0
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 2
    - allow-leading-underscore: false
  hex-length: 2
  hex-notation: 2
  id-name-format:
    - 2
    - allow-leading-underscore: false
  indentation:
    - 0
    - size: 4
  leading-zero: 0
  mixin-name-format:
    - 2
    - allow-leading-underscore: false
  mixins-before-declarations: 0
  nesting-depth: 0
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 2
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 0
  no-debug: 2
  no-disallowed-properties: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 1
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 0
  no-trailing-whitespace: 1
  no-trailing-zero: 2
  no-transition-all: 2
  no-universal-selectors: 0
  no-url-protocols: 1
  no-vendor-prefixes: 0
  no-warn: 0
  one-declaration-per-line: 2
  placeholder-in-extend: 0
  placeholder-name-format:
    - 2
    - allow-leading-underscore: false
  property-sort-order: 0
  property-units: 2
  pseudo-element: 2
  quotes:
    - 2
    - style: single
  shorthand-values: 2
  single-line-per-selector: 1
  space-after-bang: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 1
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-for-property: 2
  variable-name-format:
    - 0
    - allow-leading-underscore: false
  zero-unit: 2
